MACRO( THIRDPARTY_DIR thirdpartydir)
	file(GLOB thirdparty ${thirdpartydir}/* )
	set( CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} ${thirdparty} )
	file(GLOB thirdparty_lib ${thirdpartydir}/*/lib )
	file(GLOB thirdparty_bin ${thirdpartydir}/*/bin )
	LINK_DIRECTORIES( ${thirdparty_bin} )
ENDMACRO()

MACRO( INSTALL_WITH_DEPS )
	SET( COMPONENTS "RUNTIME;LIBRARY;ARCHIVE;TARGETS" )
	SET( OPTIONS "DESTINATION" )
	SET( last_COMPONENT "" )
	SET( last_OPTION "" )
	FOREACH( each ${ARGN} )
		LIST(FIND COMPONENTS ${each} list_find)
		LIST(FIND OPTIONS ${each} list_find2)
		IF(${list_find} GREATER -1 )
			SET( last_COMPONENT ${each} )
			SET( last_OPTION "" )
		ELSEIF( ${list_find2} GREATER -1 )
			SET( last_OPTION ${each} )
		ELSE()
			LIST(APPEND ${last_COMPONENT}_${last_OPTION} ${each} )
		ENDIF()
	ENDFOREACH()


ENDMACRO()
